export const panelHtml = `<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Wallet · Correos de prueba</title>
<style>body{font:16px system-ui;margin:0;background:#f4f7fb;color:#15233d}main{max-width:1100px;margin:auto;padding:28px}h1{font-size:26px}a{color:#245cc9}.box{background:white;border:1px solid #dce3ed;border-radius:12px;padding:20px;margin:18px 0}label{display:block;margin:12px 0 5px}input,select,textarea,button{font:inherit;box-sizing:border-box;border:1px solid #b9c7dc;border-radius:6px;padding:10px}input,textarea,select{width:100%;background:white}textarea{font:14px monospace}button{background:#245cc9;color:white;cursor:pointer;margin:8px 8px 0 0}button:disabled{opacity:.5}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f3f6fc;padding:12px;font-size:13px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.message{border-top:1px solid #dce3ed;padding:14px 0}.status{color:#52647c}#error{color:#b42318;white-space:pre-wrap}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style></head>
<body><main><a href="/">← Abrir wallet local</a><h1>Correos de prueba</h1><p>Este buzón simula Gmail y ejecuta los archivos actuales de Apps Script. Los consumos se envían a tu wallet local. Los mensajes y etiquetas se guardan al reiniciar.</p><p id="counts" class="status"></p><p id="error" role="alert"></p>
<div class="grid"><section class="box"><h2>Crear correo</h2><form id="message"><label for="format">Formato de ejemplo</label><select id="format"><option value="itau">Aviso Itaú</option><option value="automation">Automation Wallet</option><option value="unknown">Correo no reconocido</option></select><label for="from">Remitente</label><input id="from" required><label for="subject">Asunto</label><input id="subject" required><label for="date">Fecha</label><input id="date" type="datetime-local" required><label for="body">Cuerpo</label><textarea id="body" rows="8" required></textarea><button>Guardar pendiente</button></form></section>
<section class="box"><h2>Destinos</h2><p>Podés cambiar el mapeo igual que WALLET_TARGETS_JSON. Una tarjeta conocida se asigna inicialmente por sus últimos cuatro dígitos.</p><p id="entities" class="status"></p><form id="targets"><label for="mapping">Mapeo JSON</label><textarea id="mapping" rows="12"></textarea><button>Guardar destinos</button></form></section></div>
<section class="box"><h2>Buzón</h2><button id="run">Ejecutar processPendingEmails</button><button id="refresh">Actualizar</button><div id="threads"></div></section>
<section class="box"><h2>Última ejecución</h2><pre id="logs">Todavía no se ejecutó el trigger.</pre><details><summary>Payloads y respuestas de la API</summary><pre id="deliveries"></pre></details></section></main>
<script type="module">
const el = id => document.getElementById(id); let state;
async function request(route, data) { const response = await fetch('/__sandbox/'+route, data === undefined ? {} : {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); const result=await response.json(); if(!response.ok) throw new Error(result.error || 'Error local'); return result; }
async function action(work) { el('error').textContent=''; try { await work(); } catch(error) { el('error').textContent=error.message; } }
function example() { const digits=state?.creditCards[0]?.lastFour || '1234'; const name=state?.creditCards[0]?.name || 'INTERNACIONAL'; const format=el('format').value; el('from').value=format==='itau'?'comunicaciones@itau.com.uy':'pruebas@example.test'; el('subject').value=format==='itau'?'Aviso de consumo aprobado con tarjeta de crédito':'Consumo de prueba'; el('body').value=format==='itau'?'Importe: 125,50 UYU\\nComercio: TEST MARKET\\nVISA nro. ****'+digits:format==='automation'?'Tarjeta / Pase: '+name+'\\nNombre / Contraparte: TEST MARKET\\nMonto: UYU 125,50':'Este correo no tiene un consumo reconocible.'; }
async function refresh() { state=await request('state'); el('counts').textContent=state.counts.records+' movimientos · '+state.counts.creditCardRecords+' consumos de tarjeta · '+state.threads.length+' threads'; el('mapping').value=JSON.stringify(state.targets,null,2); el('entities').textContent=[...state.accounts.map(x=>'Cuenta: '+x.name+' ('+x.currency+') '+x.id),...state.creditCards.map(x=>'Tarjeta: '+x.name+' · '+x.lastFour+' · '+x.id)].join(' | '); el('threads').replaceChildren(); for(const thread of state.threads) { const box=document.createElement('div'); box.className='message'; const title=document.createElement('strong'); title.textContent=thread.labels.join(', '); box.append(title); for(const message of thread.messages) { const pre=document.createElement('pre'); pre.textContent=message.subject+'\\n'+message.from+' · '+message.date+'\\n'+message.body; box.append(pre); } const retry=document.createElement('button'); retry.textContent='Volver a pendiente / probar duplicado'; retry.onclick=()=>action(async()=>{await request('requeue',{threadId:thread.id});await refresh();}); box.append(retry); el('threads').append(box); } el('logs').textContent=state.lastRun?.logs.join('\\n') || 'Todavía no se ejecutó el trigger.'; el('deliveries').textContent=JSON.stringify(state.lastRun?.deliveries || [],null,2); }
el('date').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
el('format').onchange=example;
el('message').onsubmit=event=>{event.preventDefault();action(async()=>{await request('messages',{from:el('from').value,subject:el('subject').value,date:new Date(el('date').value).toISOString(),body:el('body').value});await refresh();});};
el('targets').onsubmit=event=>{event.preventDefault();action(async()=>{await request('targets',JSON.parse(el('mapping').value));await refresh();});};
el('refresh').onclick=()=>action(refresh);
el('run').onclick=()=>action(async()=>{el('run').disabled=true;el('logs').textContent='Procesando correos…';try{await request('run',{});await refresh();}finally{el('run').disabled=false;}});
await action(async()=>{await refresh();example();});
</script></body></html>`;
