import EmbeddedPostgres from "embedded-postgres";
import { Pool, types, type PoolClient } from "pg";
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createServer } from "node:net";
import { neonConfig } from "@neondatabase/serverless";
import { LOCAL_DATABASE_URL } from "./database.js";

/** Real independent connections, with the same Neon HTTP batch protocol as production. */
export async function createPostgresTestDatabase() {
  const directory = await mkdtemp(join(tmpdir(), "wallet-pg-test-"));
  const socket = createServer();
  await new Promise<void>((resolve) => socket.listen(0, "127.0.0.1", resolve));
  const address = socket.address();
  if (!address || typeof address === "string") throw new Error("Missing test port");
  const port = address.port;
  await new Promise<void>((resolve) => socket.close(() => resolve()));
  const pg = new EmbeddedPostgres({ databaseDir: directory, port, user: "wallet_test", password: "local-test-only", persistent: true, postgresFlags: ["-h", "127.0.0.1"], onLog: () => {}, onError: () => {} });
  await pg.initialise();
  await pg.start();
  const pool = new Pool({ host: "127.0.0.1", port, user: "wallet_test", password: "local-test-only", database: "postgres", max: 8 });
  const connectedClients = new Set<PoolClient>();
  pool.on("connect", client => {
    connectedClients.add(client);
    client.once("end", () => connectedClients.delete(client));
  });
  async function closePool() {
    // pg-pool resolves end() after removing clients, before their sockets end.
    // Stopping PostgreSQL in that gap can emit unhandled 57P01 errors in CI.
    const disconnected = [...connectedClients].map(client => new Promise<void>(resolve => client.once("end", resolve)));
    await pool.end();
    await Promise.all(disconnected);
  }
  const folder = new URL("../../drizzle/migrations/", import.meta.url);
  const journal = JSON.parse(await readFile(new URL("meta/_journal.json", folder), "utf8")) as { entries: { tag: string }[] };
  try {
    for (const entry of journal.entries) {
      try { await pool.query(await readFile(new URL(`${entry.tag}.sql`, folder), "utf8")); }
      catch (error) { throw new Error(`Migration ${entry.tag} failed`, { cause: error }); }
    }
  } catch (error) { await closePool(); await pg.stop(); await rm(directory, { recursive: true, force: true, maxRetries: 20, retryDelay: 100 }); throw error; }
  const previousUrl = process.env.DATABASE_URL;
  const previousFetch = neonConfig.fetchFunction, previousEndpoint = neonConfig.fetchEndpoint;
  process.env.DATABASE_URL = LOCAL_DATABASE_URL;
  neonConfig.fetchEndpoint = "http://wallet.local/sql";
  neonConfig.fetchFunction = async (input: string, options: RequestInit) => {
    if (input !== "http://wallet.local/sql" || new Headers(options.headers).get("Neon-Connection-String") !== LOCAL_DATABASE_URL) throw new Error("Refused non-local database");
    const body = JSON.parse(String(options.body)) as { query?: string; params?: unknown[]; queries?: { query: string; params: unknown[] }[] };
    const client = await pool.connect();
    const execute = async (query: string, params: unknown[] = []) => {
      const result = await client.query({ text: query, values: params, rowMode: "array", types: { getTypeParser: (oid: number) => [16,20,21,23,700,701,1082,1114,1184,1700,114,3802].includes(oid) ? (value: string) => value : types.getTypeParser(oid) } });
      return { fields: result.fields, rows: result.rows, rowCount: result.rowCount, command: result.command };
    };
    try {
      if (!body.queries) return Response.json(await execute(body.query!, body.params));
      await client.query("BEGIN");
      const results = [];
      for (const query of body.queries) results.push(await execute(query.query, query.params));
      await client.query("COMMIT");
      return Response.json({ results });
    } catch (error) {
      await client.query("ROLLBACK");
      const failure = error as { message: string; code?: string; detail?: string; constraint?: string };
      return Response.json({ message: failure.message, code: failure.code, detail: failure.detail, constraint: failure.constraint }, { status: 400 });
    } finally { client.release(); }
  };
  return { pool, close: async () => {
    neonConfig.fetchFunction = previousFetch; neonConfig.fetchEndpoint = previousEndpoint;
    if (previousUrl === undefined) delete process.env.DATABASE_URL; else process.env.DATABASE_URL = previousUrl;
    await closePool(); await pg.stop();
    // The directory is freshly generated by mkdtemp above and contains only this fixture.
    await rm(directory, { recursive: true, force: true, maxRetries: 20, retryDelay: 100 });
  } };
}
