import {
  Apple,
  Baby,
  Banknote,
  Beef,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Car,
  ChefHat,
  CircleDollarSign,
  Coffee,
  Coins,
  CreditCard,
  Croissant,
  Dumbbell,
  Flag,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Hammer,
  HeartPulse,
  Home,
  Key,
  Landmark,
  Laptop,
  Lightbulb,
  ParkingCircle,
  Phone,
  PiggyBank,
  Plane,
  Plug,
  ReceiptText,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Stethoscope,
  Tag,
  Target,
  Ticket,
  Train,
  Tv,
  Utensils,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  type LucideIcon,
} from "lucide-react";

export const categoryIconOptions = [
  { value: "tag", label: "General", Icon: Tag },
  { value: "home", label: "Home", Icon: Home },
  { value: "building-2", label: "Property", Icon: Building2 },
  { value: "key", label: "Rentals", Icon: Key },
  { value: "plug", label: "Utilities", Icon: Plug },
  { value: "lightbulb", label: "Electricity", Icon: Lightbulb },
  { value: "wifi", label: "Wifi", Icon: Wifi },
  { value: "utensils", label: "Food", Icon: Utensils },
  { value: "chef-hat", label: "Restaurant", Icon: ChefHat },
  { value: "shopping-cart", label: "Market", Icon: ShoppingCart },
  { value: "apple", label: "Produce", Icon: Apple },
  { value: "beef", label: "Butcher", Icon: Beef },
  { value: "croissant", label: "Bakery", Icon: Croissant },
  { value: "coffee", label: "Coffee", Icon: Coffee },
  { value: "wine", label: "Drinks", Icon: Wine },
  { value: "shopping-bag", label: "Shopping", Icon: ShoppingBag },
  { value: "shirt", label: "Clothing", Icon: Shirt },
  { value: "car", label: "Vehicle", Icon: Car },
  { value: "bus", label: "Bus", Icon: Bus },
  { value: "train", label: "Train", Icon: Train },
  { value: "plane", label: "Travel", Icon: Plane },
  { value: "fuel", label: "Fuel", Icon: Fuel },
  { value: "parking-circle", label: "Parking", Icon: ParkingCircle },
  { value: "wrench", label: "Maintenance", Icon: Wrench },
  { value: "shield", label: "Insurance", Icon: Shield },
  { value: "banknote", label: "Cash", Icon: Banknote },
  { value: "coins", label: "Income", Icon: Coins },
  { value: "wallet", label: "Wallet", Icon: Wallet },
  { value: "credit-card", label: "Card", Icon: CreditCard },
  { value: "receipt-text", label: "Bills", Icon: ReceiptText },
  { value: "circle-dollar-sign", label: "Finance", Icon: CircleDollarSign },
  { value: "landmark", label: "Bank", Icon: Landmark },
  { value: "piggy-bank", label: "Savings", Icon: PiggyBank },
  { value: "briefcase", label: "Work", Icon: Briefcase },
  { value: "laptop", label: "Tech", Icon: Laptop },
  { value: "phone", label: "Phone", Icon: Phone },
  { value: "tv", label: "Media", Icon: Tv },
  { value: "heart-pulse", label: "Health", Icon: HeartPulse },
  { value: "stethoscope", label: "Medical", Icon: Stethoscope },
  { value: "dumbbell", label: "Fitness", Icon: Dumbbell },
  { value: "gamepad-2", label: "Games", Icon: Gamepad2 },
  { value: "ticket", label: "Events", Icon: Ticket },
  { value: "book-open", label: "Books", Icon: BookOpen },
  { value: "graduation-cap", label: "Education", Icon: GraduationCap },
  { value: "gift", label: "Gifts", Icon: Gift },
  { value: "baby", label: "Family", Icon: Baby },
  { value: "scissors", label: "Personal care", Icon: Scissors },
  { value: "hammer", label: "Repairs", Icon: Hammer },
  { value: "sparkles", label: "Lifestyle", Icon: Sparkles },
  { value: "target", label: "Goal", Icon: Target },
  { value: "flag", label: "Milestone", Icon: Flag },
] as const;

const categoryIconMap = Object.fromEntries(
  categoryIconOptions.map((option) => [option.value, option.Icon]),
) as Record<string, LucideIcon>;

export function getCategoryIcon(icon?: string) {
  return categoryIconMap[icon ?? ""] ?? Tag;
}
