import type { WalletDataset } from "./types.js";

export const mockWalletData: WalletDataset = {
  settings: {
    primaryCurrency: "UYU",
    primaryAccountId: "acc-bank",
    theme: "light",
    defaultDashboardPreset: "general",
    locale: "es-UY",
    includeHiddenAccountsInReports: false,
  },
  accounts: [
    {
      id: "acc-cash",
      name: "Efectivo",
      type: "cash",
      currency: "UYU",
      initialBalance: 18500,
      color: "#6D28D9",
      icon: "wallet",
      isVisible: true,
      isActive: true,
    },
    {
      id: "acc-bank",
      name: "Banco",
      type: "bank",
      currency: "UYU",
      initialBalance: 92400,
      color: "#0F766E",
      icon: "landmark",
      isVisible: true,
      isActive: true,
    },
    {
      id: "acc-card",
      name: "Tarjeta",
      type: "credit_card",
      currency: "UYU",
      initialBalance: -12500,
      color: "#DC2626",
      icon: "credit-card",
      isVisible: true,
      isActive: true,
    },
    {
      id: "acc-usd",
      name: "Ahorro USD",
      type: "savings",
      currency: "USD",
      initialBalance: 850,
      color: "#2563EB",
      icon: "piggy-bank",
      isVisible: true,
      isActive: true,
    },
    {
      id: "acc-hidden",
      name: "Reserva oculta",
      type: "savings",
      currency: "UYU",
      initialBalance: 24000,
      color: "#64748B",
      icon: "archive",
      isVisible: false,
      isActive: true,
    },
  ],
  categories: [
    {
      id: "cat-groceries",
      name: "Groceries",
      color: "#14B8A6",
      icon: "utensils",
    },
    {
      id: "cat-groceries-supermarket",
      name: "Supermarket",
      parentId: "cat-groceries",
      color: "#2DD4BF",
      icon: "shopping-cart",
    },
    {
      id: "cat-groceries-greengrocer",
      name: "Greengrocer",
      parentId: "cat-groceries",
      color: "#22C55E",
      icon: "apple",
    },
    {
      id: "cat-groceries-butcher",
      name: "Butcher",
      parentId: "cat-groceries",
      color: "#EF4444",
      icon: "beef",
    },
    {
      id: "cat-groceries-bakery",
      name: "Bakery",
      parentId: "cat-groceries",
      color: "#F59E0B",
      icon: "croissant",
    },
    {
      id: "cat-shopping",
      name: "Shopping",
      color: "#38BDF8",
      icon: "shopping-bag",
    },
    {
      id: "cat-shopping-clothing",
      name: "Clothing & Footwear",
      parentId: "cat-shopping",
      color: "#7DD3FC",
      icon: "shirt",
    },
    {
      id: "cat-housing",
      name: "Housing",
      color: "#F59E0B",
      icon: "home",
    },
    {
      id: "cat-housing-rent",
      name: "Rent",
      parentId: "cat-housing",
      color: "#FBBF24",
      icon: "key",
    },
    {
      id: "cat-housing-utilities",
      name: "Utilities",
      parentId: "cat-housing",
      color: "#F97316",
      icon: "plug",
    },
    {
      id: "cat-transport",
      name: "Transportation",
      color: "#64748B",
      icon: "bus",
    },
    {
      id: "cat-transport-flights",
      name: "Flights",
      parentId: "cat-transport",
      color: "#94A3B8",
      icon: "plane",
    },
    {
      id: "cat-life",
      name: "Life & Entertainment",
      color: "#7C3AED",
      icon: "sparkles",
    },
    {
      id: "cat-life-restaurants",
      name: "Restaurants",
      parentId: "cat-life",
      color: "#8B5CF6",
      icon: "chef-hat",
    },
    {
      id: "cat-life-fitness",
      name: "Fitness",
      parentId: "cat-life",
      color: "#C084FC",
      icon: "dumbbell",
    },
    {
      id: "cat-vehicle",
      name: "Vehicle",
      color: "#A855F7",
      icon: "car",
    },
    {
      id: "cat-income",
      name: "Income",
      color: "#22C55E",
      icon: "coins",
    },
    {
      id: "cat-freelance",
      name: "Freelance",
      parentId: "cat-income",
      color: "#06B6D4",
      icon: "briefcase",
    },
  ],
  tags: [
    { id: "tag-trip", name: "viaje", color: "#0EA5E9", isActive: true },
    { id: "tag-emergency", name: "emergencia", color: "#EF4444", isActive: true },
    { id: "tag-fixed", name: "fijo", color: "#64748B", isActive: true },
    { id: "tag-cut", name: "recorte", color: "#F97316", isActive: true },
    { id: "tag-pleasure", name: "placer", color: "#A855F7", isActive: true },
  ],
  records: [
    {
      id: "rec-income-1",
      type: "income",
      amount: 43013,
      currency: "UYU",
      accountId: "acc-bank",
      categoryId: "cat-income",
      counterpartyName: "Pago Amigo",
      tagIds: [],
      paymentType: "transfer",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-01T12:30:00.000Z",
      note: "Ingreso mensual",
    },
    {
      id: "rec-rent",
      type: "expense",
      amount: 18500,
      currency: "UYU",
      accountId: "acc-bank",
      categoryId: "cat-housing-rent",
      counterpartyName: "Alquiler",
      tagIds: ["tag-fixed"],
      paymentType: "transfer",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-02T09:00:00.000Z",
      note: "Alquiler",
      isFixed: true,
    },
    {
      id: "rec-food-1",
      type: "expense",
      amount: 3840,
      currency: "UYU",
      accountId: "acc-card",
      categoryId: "cat-groceries-supermarket",
      counterpartyName: "Supermercado",
      tagIds: [],
      paymentType: "credit",
      paymentStatus: "pending",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-04T18:20:00.000Z",
    },
    {
      id: "rec-transfer-usd",
      type: "transfer",
      amount: 12000,
      currency: "UYU",
      accountId: "acc-bank",
      destinationAccountId: "acc-hidden",
      tagIds: ["tag-emergency"],
      paymentType: "transfer",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-07T15:10:00.000Z",
      note: "Reserva interna para emergencias",
    },
    {
      id: "rec-trip-flight",
      type: "expense",
      amount: 9200,
      currency: "UYU",
      accountId: "acc-card",
      categoryId: "cat-transport-flights",
      counterpartyName: "Aerolinea",
      tagIds: ["tag-trip"],
      paymentType: "credit",
      paymentStatus: "pending",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-09T22:15:00.000Z",
      note: "Pasaje para viaje",
    },
    {
      id: "rec-life",
      type: "expense",
      amount: 2600,
      currency: "UYU",
      accountId: "acc-cash",
      categoryId: "cat-life-restaurants",
      counterpartyName: "Pago Amigo",
      tagIds: ["tag-pleasure"],
      paymentType: "cash",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-12T23:30:00.000Z",
    },
    {
      id: "rec-shop",
      type: "expense",
      amount: 890,
      currency: "UYU",
      accountId: "acc-cash",
      categoryId: "cat-shopping-clothing",
      counterpartyName: "Clothes & Footwear",
      tagIds: ["tag-cut"],
      paymentType: "cash",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-14T19:53:00.000Z",
    },
    {
      id: "rec-freelance",
      type: "income",
      amount: 320,
      currency: "USD",
      accountId: "acc-usd",
      categoryId: "cat-freelance",
      tagIds: ["tag-trip"],
      paymentType: "transfer",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 39.2,
      occurredAt: "2026-06-14T20:20:00.000Z",
      note: "Freelance pequeno",
    },
  ],
  goals: [
    {
      id: "goal-trip",
      name: "Viaje a Brasil",
      targetAmount: 50000,
      currency: "UYU",
      color: "#0EA5E9",
      icon: "plane",
      isVisible: true,
      deadline: "2026-09-20",
      status: "active",
      tagIds: ["tag-trip"],
      accountId: "acc-bank",
      note: "Pasajes, alojamiento y gastos principales",
    },
    {
      id: "goal-emergency",
      name: "Fondo de emergencia",
      targetAmount: 120000,
      currency: "UYU",
      color: "#EF4444",
      icon: "shield",
      isVisible: true,
      status: "active",
      tagIds: ["tag-emergency"],
      accountId: "acc-usd",
    },
  ],
  goalReservations: [
    {
      id: "gres-trip-1",
      goalId: "goal-trip",
      accountId: "acc-bank",
      amount: 15000,
      currency: "UYU",
      createdAt: "2026-06-05T11:00:00.000Z",
      note: "Separado para senar alojamiento",
    },
    {
      id: "gres-emergency-1",
      goalId: "goal-emergency",
      accountId: "acc-usd",
      amount: 450,
      currency: "USD",
      createdAt: "2026-06-06T11:00:00.000Z",
    },
  ],
  budgets: [
    {
      id: "budget-general",
      name: "Gasto mensual",
      limitAmount: 65000,
      currency: "UYU",
      period: "monthly",
      color: "#0F766E",
      isActive: true,
    },
    {
      id: "budget-food",
      name: "Comida",
      limitAmount: 14000,
      currency: "UYU",
      period: "monthly",
      categoryId: "cat-groceries",
      color: "#14B8A6",
      isActive: true,
    },
    {
      id: "budget-trip",
      name: "Viaje",
      limitAmount: 50000,
      currency: "UYU",
      period: "monthly",
      tagId: "tag-trip",
      goalId: "goal-trip",
      color: "#0EA5E9",
      isActive: true,
    },
  ],
  exchangeRates: [
    {
      id: "fx-usd-uyu",
      fromCurrency: "USD",
      toCurrency: "UYU",
      rate: 39.2,
      date: "2026-06-15",
    },
    {
      id: "fx-brl-uyu",
      fromCurrency: "BRL",
      toCurrency: "UYU",
      rate: 7.3,
      date: "2026-06-15",
    },
  ],
  investments: [
    {
      id: "inv-1",
      name: "Fondo conservador",
      type: "fund",
      amountInvested: 18000,
      currentValue: 18750,
      currency: "UYU",
      isVisible: true,
      startedAt: "2026-03-10",
      note: "Seguimiento manual",
    },
  ],
  debts: [
    {
      id: "debt-1",
      name: "Prestamo familiar",
      originalAmount: 30000,
      pendingAmount: 18000,
      currency: "UYU",
      status: "active",
      startedAt: "2026-01-15",
      dueAt: "2026-12-15",
    },
  ],
  installmentPlans: [
    {
      id: "inst-1",
      name: "Notebook",
      totalAmount: 42000,
      currency: "UYU",
      installmentsTotal: 12,
      installmentsPaid: 5,
      accountId: "acc-card",
      categoryId: "cat-shopping",
      nextPaymentAt: "2026-07-05",
    },
  ],
};
