import type { WalletDataset } from "./types";

export const mockWalletData: WalletDataset = {
  settings: {
    primaryCurrency: "UYU",
    theme: "light",
    defaultDashboardPreset: "general",
    locale: "es-UY",
    includeHiddenAccountsInReports: false,
  },
  accounts: [
    {
      id: "acc-cash",
      name: "Efectivo",
      type: "cash",
      currency: "UYU",
      initialBalance: 18500,
      color: "#6D28D9",
      icon: "wallet",
      isVisible: true,
      isActive: true,
    },
    {
      id: "acc-bank",
      name: "Banco",
      type: "bank",
      currency: "UYU",
      initialBalance: 92400,
      color: "#0F766E",
      icon: "landmark",
      isVisible: true,
      isActive: true,
    },
    {
      id: "acc-card",
      name: "Tarjeta",
      type: "credit_card",
      currency: "UYU",
      initialBalance: -12500,
      color: "#DC2626",
      icon: "credit-card",
      isVisible: true,
      isActive: true,
    },
    {
      id: "acc-usd",
      name: "Ahorro USD",
      type: "savings",
      currency: "USD",
      initialBalance: 850,
      color: "#2563EB",
      icon: "piggy-bank",
      isVisible: true,
      isActive: true,
    },
    {
      id: "acc-hidden",
      name: "Reserva oculta",
      type: "savings",
      currency: "UYU",
      initialBalance: 24000,
      color: "#64748B",
      icon: "archive",
      isVisible: false,
      isActive: true,
    },
  ],
  categories: [
    {
      id: "cat-food",
      name: "Food & Drinks",
      type: "expense",
      color: "#14B8A6",
      icon: "utensils",
      isActive: true,
    },
    {
      id: "cat-shopping",
      name: "Shopping",
      type: "expense",
      color: "#38BDF8",
      icon: "shopping-bag",
      isActive: true,
    },
    {
      id: "cat-housing",
      name: "Housing",
      type: "expense",
      color: "#F59E0B",
      icon: "home",
      isActive: true,
    },
    {
      id: "cat-transport",
      name: "Transportation",
      type: "expense",
      color: "#64748B",
      icon: "bus",
      isActive: true,
    },
    {
      id: "cat-life",
      name: "Life & Entertainment",
      type: "expense",
      color: "#7C3AED",
      icon: "sparkles",
      isActive: true,
    },
    {
      id: "cat-vehicle",
      name: "Vehicle",
      type: "expense",
      color: "#A855F7",
      icon: "car",
      isActive: true,
    },
    {
      id: "cat-income",
      name: "Income",
      type: "income",
      color: "#22C55E",
      icon: "coins",
      isActive: true,
    },
    {
      id: "cat-freelance",
      name: "Freelance",
      type: "income",
      color: "#06B6D4",
      icon: "briefcase",
      isActive: true,
    },
  ],
  tags: [
    { id: "tag-trip", name: "viaje", color: "#0EA5E9", isActive: true },
    { id: "tag-emergency", name: "emergencia", color: "#EF4444", isActive: true },
    { id: "tag-fixed", name: "fijo", color: "#64748B", isActive: true },
    { id: "tag-cut", name: "recorte", color: "#F97316", isActive: true },
    { id: "tag-pleasure", name: "placer", color: "#A855F7", isActive: true },
  ],
  counterparties: [
    { id: "cp-paypal", name: "Pago Amigo", color: "#22C55E", isActive: true },
    { id: "cp-market", name: "Supermercado", color: "#14B8A6", isActive: true },
    { id: "cp-rent", name: "Alquiler", color: "#F59E0B", isActive: true },
    { id: "cp-ute", name: "UTE", color: "#64748B", isActive: true },
    { id: "cp-airline", name: "Aerolinea", color: "#0EA5E9", isActive: true },
    { id: "cp-shop", name: "Clothes & Footwear", color: "#38BDF8", isActive: true },
  ],
  records: [
    {
      id: "rec-income-1",
      type: "income",
      amount: 43013,
      currency: "UYU",
      accountId: "acc-bank",
      categoryId: "cat-income",
      counterpartyId: "cp-paypal",
      tagIds: [],
      paymentType: "transfer",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-01T12:30:00.000Z",
      note: "Ingreso mensual",
    },
    {
      id: "rec-rent",
      type: "expense",
      amount: 18500,
      currency: "UYU",
      accountId: "acc-bank",
      categoryId: "cat-housing",
      counterpartyId: "cp-rent",
      tagIds: ["tag-fixed"],
      paymentType: "transfer",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-02T09:00:00.000Z",
      note: "Alquiler",
      isFixed: true,
    },
    {
      id: "rec-food-1",
      type: "expense",
      amount: 3840,
      currency: "UYU",
      accountId: "acc-card",
      categoryId: "cat-food",
      counterpartyId: "cp-market",
      tagIds: [],
      paymentType: "credit",
      paymentStatus: "pending",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-04T18:20:00.000Z",
    },
    {
      id: "rec-transfer-usd",
      type: "transfer",
      amount: 12000,
      currency: "UYU",
      accountId: "acc-bank",
      destinationAccountId: "acc-hidden",
      tagIds: ["tag-emergency"],
      paymentType: "transfer",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-07T15:10:00.000Z",
      note: "Reserva interna para emergencias",
    },
    {
      id: "rec-trip-flight",
      type: "expense",
      amount: 9200,
      currency: "UYU",
      accountId: "acc-card",
      categoryId: "cat-transport",
      counterpartyId: "cp-airline",
      tagIds: ["tag-trip"],
      paymentType: "credit",
      paymentStatus: "pending",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-09T22:15:00.000Z",
      note: "Pasaje para viaje",
    },
    {
      id: "rec-life",
      type: "expense",
      amount: 2600,
      currency: "UYU",
      accountId: "acc-cash",
      categoryId: "cat-life",
      counterpartyId: "cp-paypal",
      tagIds: ["tag-pleasure"],
      paymentType: "cash",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-12T23:30:00.000Z",
    },
    {
      id: "rec-shop",
      type: "expense",
      amount: 890,
      currency: "UYU",
      accountId: "acc-cash",
      categoryId: "cat-shopping",
      counterpartyId: "cp-shop",
      tagIds: ["tag-cut"],
      paymentType: "cash",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 1,
      occurredAt: "2026-06-14T19:53:00.000Z",
    },
    {
      id: "rec-freelance",
      type: "income",
      amount: 320,
      currency: "USD",
      accountId: "acc-usd",
      categoryId: "cat-freelance",
      tagIds: ["tag-trip"],
      paymentType: "transfer",
      paymentStatus: "cleared",
      exchangeRateToPrimary: 39.2,
      occurredAt: "2026-06-14T20:20:00.000Z",
      note: "Freelance pequeno",
    },
  ],
  goals: [
    {
      id: "goal-trip",
      name: "Viaje a Brasil",
      targetAmount: 50000,
      currency: "UYU",
      color: "#0EA5E9",
      icon: "plane",
      deadline: "2026-09-20",
      status: "active",
      tagIds: ["tag-trip"],
      accountId: "acc-bank",
      note: "Pasajes, alojamiento y gastos principales",
    },
    {
      id: "goal-emergency",
      name: "Fondo de emergencia",
      targetAmount: 120000,
      currency: "UYU",
      color: "#EF4444",
      icon: "shield",
      status: "active",
      tagIds: ["tag-emergency"],
      accountId: "acc-usd",
    },
  ],
  goalReservations: [
    {
      id: "gres-trip-1",
      goalId: "goal-trip",
      accountId: "acc-bank",
      amount: 15000,
      currency: "UYU",
      createdAt: "2026-06-05T11:00:00.000Z",
      note: "Separado para senar alojamiento",
    },
    {
      id: "gres-emergency-1",
      goalId: "goal-emergency",
      accountId: "acc-usd",
      amount: 450,
      currency: "USD",
      createdAt: "2026-06-06T11:00:00.000Z",
    },
  ],
  budgets: [
    {
      id: "budget-general",
      name: "Gasto mensual",
      limitAmount: 65000,
      currency: "UYU",
      period: "monthly",
      color: "#0F766E",
      isActive: true,
    },
    {
      id: "budget-food",
      name: "Comida",
      limitAmount: 14000,
      currency: "UYU",
      period: "monthly",
      categoryId: "cat-food",
      color: "#14B8A6",
      isActive: true,
    },
    {
      id: "budget-trip",
      name: "Viaje",
      limitAmount: 50000,
      currency: "UYU",
      period: "monthly",
      tagId: "tag-trip",
      goalId: "goal-trip",
      color: "#0EA5E9",
      isActive: true,
    },
  ],
  exchangeRates: [
    {
      id: "fx-usd-uyu",
      fromCurrency: "USD",
      toCurrency: "UYU",
      rate: 39.2,
      date: "2026-06-15",
    },
    {
      id: "fx-brl-uyu",
      fromCurrency: "BRL",
      toCurrency: "UYU",
      rate: 7.3,
      date: "2026-06-15",
    },
  ],
  investments: [
    {
      id: "inv-1",
      name: "Fondo conservador",
      type: "fund",
      amountInvested: 18000,
      currentValue: 18750,
      currency: "UYU",
      startedAt: "2026-03-10",
      note: "Seguimiento manual",
    },
  ],
  debts: [
    {
      id: "debt-1",
      name: "Prestamo familiar",
      originalAmount: 30000,
      pendingAmount: 18000,
      currency: "UYU",
      status: "active",
      startedAt: "2026-01-15",
      dueAt: "2026-12-15",
    },
  ],
  installmentPlans: [
    {
      id: "inst-1",
      name: "Notebook",
      totalAmount: 42000,
      currency: "UYU",
      installmentsTotal: 12,
      installmentsPaid: 5,
      accountId: "acc-card",
      categoryId: "cat-shopping",
      nextPaymentAt: "2026-07-05",
    },
  ],
};
